### PR TITLE
Neither Debian nor Ubuntu mirrors host the "i18n/Index"

### PR DESCRIPTION
**Pull request by chutzimir**
The translation "Index" is documented at
https://wiki.debian.org/DebianRepository/Format#A.22Translation.22_indices

	The directory dists/$DIST/$COMP/i18n/ contains the file index,
	with a SHA1 field listing the description indices in that
	directory

Funny enough, the Debian mirrors do not host an `i18n/Index` file. E.g.,
there is no http://ftp.debian.org/debian/dists/stable/main/i18n/Index,
but the files in the directory are indexed in
http://ftp.debian.org/debian/dists/stable/InRelease instead.

Ubuntu mirrors do host the i18n/Index, but the files under i18n are
also indexed in the Release file.

Since we find the translation files while parsing the Release, there is
no need to look into a separate index for them. This index does not have
the by-hash checksums so it is not very useful anyway.

### CODE REVIEW

**Comment by chutzimir** [comment]
Either way is fine, but I'm curious what is using this Index. Is apt actually pulling it?

**Comment by Stifler6996** [comment]
I need to look into it more. From that post, it appears that 1. The file should have been generated by Debian/Ubuntu. 2. We were not handling it well if it did not exist.
I can see we now handle the point 2. 

In that conversation it seems that Ubuntu regresses again in 2015. Today, it looks like its been generally forgotten about, but this is where we need to be cautious. There may be repos still using sha1 and i18n/Index might be in use (or needed?).

Since it doesn't cause any immediate problem, I think it wise to let it lay. Hopefully we can dig up more story around this, and get a better understanding of why it existed/disappeared/existed again and now appears to be ignored by the major distroreleases.

Happy to bring this back if we can confirm it is now redundant.

**Comment by chutzimir** [comment]
For what it's worth, I found this, what seems to be, authoritative article: https://www.chiark.greenend.org.uk/~cjwatson/blog/no-more-hash-sum-mismatch-errors.html

It gives a good history of how the structure evolved, and also why downloading everything but the top InRelease file is error prone :)

My only concern with leaving that code in "as is" is that I don't even know if it is working after the latest "by-hash" download. There seems to be no obvious way to test it if I don't have a real-life example of a repository using it.

**Comment by chutzimir** [comment]
In fact, my concern is with [this comment](https://github.com/Stifler6996/apt-mirror/blob/0f10eb8fa212df5b22ecb2f2cb9b07fc21b27a25/apt-mirror#L647) in `sub process_translation_index`

```
Fall back to parsing dists/$DIST/Release if i18n/Index is not found
```

It's supposed to be the other way around - first we try the `InRelease`, and then the `i18n/Index`.

**Comment by Stifler6996** [comment]
[https://wiki.debian.org/DebianRepository/Format](https://wiki.debian.org/DebianRepository/Format)
My concern is that it is still mentioned in this document. It doesn't mean that its correct or used though. I will re-read the article you posted again to make sure I understand it.

I certainly agree this could be tidied up. Look for InRelease and process by-hash etc. If this is successful, then that's it, and move on.
However, if that fails, perhaps we should at least be making an attempt to find the internationalisation folder (i18n) ?

My guess (pure speculation) is that this section was written around the time of implementation of i18n, ~2011. This would explain the order of events in current code [that you commented on](https://github.com/Stifler6996/apt-mirror/pull/24#issuecomment-1132493591). And then, its never been reviewed or updated when InRelease took on a more primary role in ~2016.

**Comment by chutzimir** [comment]
You motivated me to dig more into this. So, I found [this commit from 2012](https://github.com/Debian/apt/commit/8e3900d0d7efc11d538b944ed1d9e4e3d5286ff6):

Let me quote the commit message because it is hilarious:

```
* apt-pkg/acquire-item.cc:
  - drop support for i18n/Index file (introduced in 0.8.11) and use
    the Release file instead to get the Translations (Closes: #649314)
* ftparchive/writer.cc:
  - add 'Translation-*' to the default patterns

i18n/Index was never used outside debian - and even here it isn't used
consistently as only 'main' has such a file. As the Release file now
includes the Translation-* files we therefore drop support for i18n/Index.

A version supporting it was never part of a debian release and still
supporting it would mean that we get 99% of the time a 404 as response
to the request anyway and confuse archive maintainers who want to
provide all files APT tries to acquire.
```

**Comment by chutzimir** [comment]
I replaced the commit message because it is a much better explanation :)

**Comment by Stifler6996** [comment]
oh dear! Well I guess [good] ideas come and go. At least we now have a confirmation from Debian apt themselves. Nice find, well done.

I have just completed testing on the last two commits, so I will wait 6hr before I finalise this addition and then test against mirrors. Just so I am not hammering or abusing the main repos.

**Comment by chutzimir** [comment]
I am all for trying things out, and just as importantly - cleaning up. All my respect to that extremely fast turnout to cleaning it up.

**Pull request merged**
