### PR TITLE
Added support for cnf directory

### PR DESCRIPTION
**Pull request by Stifler6996**
added download url to support the /cnf/Commands-<$arch>.xz files

### CODE REVIEW

**Comment by rdica** [comment]
Testing. I'm mirroring xenial, bionic, and now focal. My test focal instance seems to be working with my local mirror now.

**Comment by RWoodring79** [comment]
@Stifler6996 I hate to comment on a closed PR, but I did not know where else to make this comment. When I try to mirror any of the Focal repos, I get `Failed to fetch file` errors for some of my `cnf/Commands-*` files. I wonder if this could be caused by my attempt to mirror only i386/amd64 targets. This is how I have my mirror.list set up:
```
deb-amd64 http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
deb-i386 http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
```
I do not see any warning/errors while running apt-mirror, but when I run `apt update` pointing to my mirror, it fails to time the `Commands-amd64` four times, then gives me an error as shown here:
```
...
Get:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
Ign:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata
...
Get:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
Ign:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata
...
Get:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
Ign:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata
...
Get:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [111 kB]
Err:11 file:/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata
  File not found - /home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu/dists/focal/main/cnf/Commands-amd64 (2: No such file or directory)
```
When I list the contents of the `/home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu/dists/focal/main/cnf/` folder, it contains `Commands-i386` but not `Commands-amd64`.
```
user@mirror:~/git/apt-mirror-Stifler6996$ ls -la /home/user/git/apt-mirror-Stifler6996/all/mirror/us.archive.ubuntu.com/ubuntu/dists/focal/main/cnf/
total 28
drwxrwxr-x 2 user user  4096 Aug 17 10:15 .
drwxrwxr-x 6 user user  4096 Aug 17 10:20 ..
-rw-rw-r-- 1 user user 19948 Apr 23  2020 Commands-i386.xz
```

**Comment by Stifler6996** [comment]
Not sure what's going on there. I am doing exactly the same as you, but I'm not even getting i386. I am only mirroring deb-amd64 and deb-arm64.
But whilst there is no error in mirror, it is only mirroring what exists in the main repo. So if for some reason the Commands-amd64 does not exist in the repo you are mirroring from, then it wont copy - this is not an "error" so you wouldnt see anything.

Its possible that you attempted to mirror during a time that the main repo was being updated?

**Comment by RWoodring79** [comment]
Just to follow up, I think I was doing something wrong. Not sure if it was permissions or paths or what, but after blowing away the dists folder and re-fetching files, the cnf folders contain the right files. Still fighting other issues, but I suspect they are also within my setup. I deleted my previous comment because I do not want to lead anyone else astray with my misinformation.

**Comment by Stifler6996** [comment]
Thanks!

**Pull request merged**
