### PR TITLE
Download from by-hash for a consistent mirror

### PR DESCRIPTION
**Pull request by chutzimir**

### CODE REVIEW

**Comment by chutzimir** [comment]
Rebased on latest master. This one only has one commit on top of #20, so if you get conflicts (after cherry-picking #20), let me know - I can rebase it again.

**Comment by chutzimir** [comment]
Rebased again, to help avoid conflicts.

**Comment by chutzimir** [comment]
Final rebase due to the other pull request getting in. No conflicts now. :)

**Comment by Stifler6996** [comment]
Thank you @chutzimir for all the recent updates. Much appreciated.

**Pull request merged**
