### PR TITLE
Multiple fixes and optimizations

### PR DESCRIPTION
**Pull request by chutzimir**
This is a rather large list of fixes I encountered while mirroring the following repositories for a few years now. I never submitted them due to the lack of activity on the upstream repository, but now we may get some movement.

In short:
- Fix issue with whitespace in the config file
- Optimize big downloads by better load-balancing among worker "threads"
- Clean up code duplication
- Reduce disk space usage through hard links

I would understand if the commit seems too big, and I am willing to help split it up. This has been working for me for quite a while now, but there is no guarantee it would work for everyone's use case.

```
deb  [arch=amd64]  http://archive.ubuntu.com/ubuntu                      jammy-backports   main    restricted  universe  multiverse
deb  [arch=amd64]  http://archive.ubuntu.com/ubuntu                      jammy             main    restricted  universe  multiverse
deb  [arch=amd64]  http://archive.ubuntu.com/ubuntu                      jammy-security    main    restricted  universe  multiverse
deb  [arch=amd64]  http://archive.ubuntu.com/ubuntu                      jammy-updates     main    restricted  universe  multiverse
deb  [arch=amd64]  http://dl.google.com/linux/chrome/deb                 stable            main                          
deb  [arch=amd64]  http://packages.cloud.google.com/apt                  cloud-sdk         main                          
deb  [arch=armhf]  http://ports.ubuntu.com/ubuntu-ports                  focal-backports   main    restricted  universe  multiverse
deb  [arch=armhf]  http://ports.ubuntu.com/ubuntu-ports                  focal             main    restricted  universe  multiverse
deb  [arch=armhf]  http://ports.ubuntu.com/ubuntu-ports                  focal-proposed    main    restricted  universe  multiverse
deb  [arch=armhf]  http://ports.ubuntu.com/ubuntu-ports                  focal-security    main    restricted  universe  multiverse
deb  [arch=armhf]  http://ports.ubuntu.com/ubuntu-ports                  focal-updates     main    restricted  universe  multiverse
deb  [arch=amd64]  http://ppa.launchpad.net/team-xbmc/ppa/ubuntu         jammy             main                          
deb  [arch=amd64]  https://apt.puppetlabs.com                            focal             puppet                        
deb  [arch=amd64]  https://apt.releases.hashicorp.com                    jammy             main                          
deb  [arch=amd64]  https://arkane-systems.github.io/wsl-transdebian/apt  focal             main                          
deb  [arch=amd64]  https://arkane-systems.github.io/wsl-transdebian/apt  jammy             main                          
deb  [arch=amd64]  https://cli.github.com/packages                       stable            main                          
deb  [arch=amd64]  https://downloads.plex.tv/repo/deb/                   public            main                          
deb  [arch=amd64]  http://security.ubuntu.com/ubuntu                     jammy-security    main    restricted  universe  multiverse
deb  [arch=amd64]  https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu   focal             main                          
deb  [arch=amd64]  https://repo.nordvpn.com/deb/nordvpn/debian           stable            main                          
deb  [arch=amd64]  https://repos.influxdata.com/ubuntu                   impish            stable                        
```

### CODE REVIEW

**Comment by Stifler6996** [comment]
Thanks. Let me work through this all and hopefully commit soon.

I will make some tests and hopefully get them in within the week. Sorry for the late response.

Thank  you for tackling some of these old troublesome issues.

**Review by Stifler6996 — APPROVED** [review]
this is fine. better than it was.

(https://github.com/Stifler6996/apt-mirror/pull/15/commits/f3a076e897ef3b758971f8fa974d022761dd7c59)

**Review by Stifler6996 — APPROVED** [review]
great, thanks.

Please give more explanation? Im not sure of the problem here? 
(https://github.com/Stifler6996/apt-mirror/pull/15/commits/37f15c6dbf3e79b747d7587b61ade7352a24f37f)

**Review by Stifler6996 — COMMENTED** [review]
concerns me. if the storage is on a mount of a certain fs, this may fail. (nas storage mounted in /media as a cifs)

Can we confirm or add additional checks here?

**Review by Stifler6996 — APPROVED** [review]
Refactor that has been needed for a long time.

Thank you.

**Review by Stifler6996 — APPROVED** [review]

**Comment by Stifler6996** [comment]
@chutzimir Can you please make individual pull requests for each of these. I can get a couple in quickly, but I would also like to spend more time on others.

Split them up and close this one. Thanks for your help.

**Comment by chutzimir** [comment]
@Stifler6996 I split up most of the stuff into #18, #19, and #20. I did not include the by-hash related fixes because... there is a massive problem with the way apt-mirror completely ignores [Acquire-By-Hash](https://wiki.debian.org/DebianRepository/Format#Acquire-By-Hash) which makes it almost impossible to have a consistent mirror at the moment.

**Comment by chutzimir** [comment]
My bad, I split this into #17, #18, #19, and #20. I forgot #17 in my previous comment. @Stifler6996

**Comment by chutzimir** [comment]
#17, #18, #19, #20, #21, #22 

The only one not in there is the by-hash part which needs a big rework.

**Pull request closed without merging**
