### PR TITLE
Refactor metadata parsing to reduce copy-paste

### PR DESCRIPTION
**Pull request by chutzimir**
- Refactor: Anything downloaded should be kept
- Parse the release files for all relevant metadata in one shot
- Arch all is always required

### CODE REVIEW

**Comment by chutzimir** [comment]
This request is on top of #19 otherwise we'd have too many conflicts. They are both in the same spirit, so I hope that's OK.

**Comment by chutzimir** [comment]
This also fixes #14

**Comment by chutzimir** [comment]
Just amended the last commit to put a note of the other pull request it is fixing.

**Comment by Stifler6996** [comment]
I'm getting a conflict on this merge. Not sure, but it looks like you made the changes on a fork of the original apt-mirror, rather than changes on a fork of my version.

**Comment by Stifler6996** [comment]
```
<<<<<<< metadata-refactor
download_urls( "metadata", sort keys %urls_to_download );
=======
download_urls( "translation", sort keys %urls_to_download );

######################################################################################
## DEP-11 index download

%urls_to_download = ();

sub find_dep11_files_in_release
{
    # Look in the dists/$DIST/Release file for the DEP-11 files that belong
    # to the given component and architecture.

    my $dist_uri  = shift;
    my $component = shift;
    my $arch      = shift;
    my ( $release_uri, $release_path, $line ) = '';

---<<SNIP>>---

print "]\n\n";

push( @index_urls, sort keys %urls_to_download );
download_urls( "dep11", sort keys %urls_to_download );
>>>>>>> master
```
I think I need to remove everything between ======= and >>>>>>>master.
Can you comment? I've not had to deal with this type of conflict before, because it says:
```
Refactor metadata parsing to reduce copy-paste #20
Resolving conflicts between chutzimir:metadata-refactor and Stifler6996:master and committing changes  chutzimir:metadata-refactor
```
which reads like it wants to commit to your branch?

**Comment by chutzimir** [comment]
Rebased onto the latest master. Sorry about that, I got lost in all the branches.

**Comment by Stifler6996** [comment]
heh! no problems! I have had merge problems before, but they are always my own fault, and hence know how to deal with them. This is kind of new for me! (forked branches from multiple places).

**Pull request merged**
